<div class="block block-cart-header">
    <?php $_cartQty = $this->getSummaryCount(); ?>
    <div class="block-content">
        <div class="button-show">
            <?php if ($this->canApplyMsrp()): ?>
                <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
            <?php else: ?>
                <?php 
                $cart = Mage::getModel('checkout/cart')->getQuote()->getData();
                if(isset($cart['items_qty'])){
                    $cartQty = (int)$cart['items_qty'];
                } else {
                    $cartQty = '0';
                }
                ?>
                <span class="cart-qty icon icon-arrow-right fs8"><?php echo $cartQty; ?></span>
            <?php endif; ?>
            <span class="icon icon-shopping-bag fs21"></span>
            <a href="<?php echo $this->getUrl('checkout/cart')?>"><?php echo $this->__('Shopping Cart')?></a>
        </div>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
            <div id="header-items" class="mini-popup-wrapper bs-0515-000-40">
                <span class="arrow"></span>
                <ol id="cart-sidebar" class="mini-products-list">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
                </ol>
                <div class="summary">
                    <?php echo $this->__('Total:') ?> 
                    <?php if ($this->canApplyMsrp()): ?>
                        <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                    <?php else: ?>
                        <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                        <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                            <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>
                        <?php endif; ?>
                    <?php endif; ?> 
                </div>     
                <div class="actions">
                    <button type="button" title="<?php echo $this->__('View Cart') ?>" class="button btn-view large invert fleft" onclick="window.location='<?php echo $this->getUrl('checkout/cart')?>';"><span><span><?php echo $this->__('View Cart') ?></span></span></button>                                
                    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button btn-checkout large fright" onclick="window.location='<?php echo $this->getUrl('checkout/onepage')?>'"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                </div>                              
            </div>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>

    <?php else: ?>
        <div id="header-items" class="mini-popup-wrapper empty bs-0515-000-40">
            <span class="arrow"></span>
            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        </div>
    <?php endif ?>
    </div>
</div>
